labels:
  - name: "good first issue"
    color: "7057ff"
  - name: "help wanted"
    color: "008672"
  - name: "adapter"
    color: "1d76db"
  - name: "security"
    color: "b60205"
  - name: "policy"
    color: "fbca04"
  - name: "cli"
    color: "5319e7"
  - name: "dashboard"
    color: "c5def5"
  - name: "documentation"
    color: "0075ca"
  - name: "breaking change"
    color: "d93f0b"
